### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by HoangNgo88** [roq-trading/roq-zeromq-bridge#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka

**Comment by thraneh** [comment]
Hi,

This project was done for a client who wanted to use ZeroMQ to access calculations done in C++ using Roq's client API.

It's a bridge. It's open source so anyone can use it as a template for their own needs. It's not any final code. Just an example.

With regards to other queues: I suggest you search online. There are lots of blogs and articles comparing the pros and cons of the solutions you mention.
